{ ... }:

{
  # Agenix needs the SSH host key to decrypt secrets at boot. The
  # framework-laptop host provides it through `services.openssh.enable = true`
  # only when secrets are used; otherwise the file at /etc/ssh/ssh_host_ed25519_key
  # is regenerated by agenix-cli on the build host.
  environment.etc."ssh/ssh_host_ed25519_key".source =
    "/etc/ssh/ssh_host_ed25519_key";
}
